/*
   This script creates the table crm_customers under the "sources" schema. This script uses UNION ALLs to generate fake data for the purpose of this demo. 
   https://docs.dataform.co/guides/datasets/
*/

config {
  type: "table",
  schema: "sources",
  tags: ["sources", "daily"]
}

SELECT id AS id,
       first_name AS first_name,
       last_name AS last_name,
       email AS email,
       country AS country
FROM
  crm.customer