/*
   This script creates the table stripe_charges under the "sources" schema. This script uses UNION ALLs to generate fake data for the purpose of this demo. 
   https://docs.dataform.co/guides/datasets/
*/

config {
  type: "table",
  schema: "sources",
  tags: ["sources", "daily"]
}

SELECT id AS id,
       status AS status,
       payment_method AS payment_method,
       amount AS amount
FROM
  stripe.charges